### ISSUE TITLE
SLUS-00330: Mortal Kombat Trilogy (USA)

### ISSUE THREAD

**Issue by TruKuu** [HeatXD/duckstation-fightcade-savestates#162]
**Hash**

MD5: 03553aba5d2a584f522c9b447369cb19

**Description**
This savestate is for the non (Rev 1) version. 

Aggressor: Off
Shang Tsung's Morphs: Limited - No Load
Versus Screen: Off
Buy In Screen: Off
Select Screen: Fast

Secret Konfigure is unlocked, but options remain unchanged
Savestate boots at the main menu with "Mortal Kombat" highlighted

**Savestate**
[SLUS-00330_1.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11285584/SLUS-00330_1.zip)

**Comment by bigbangblitz** [comment]
This one gives me an error in the location of the chd, but only because I'm using revision 1.

If this is not specifically for the revised disc, it should be redone as we would only be using the highest revisions of these games later.
