### ISSUE TITLE
SCUS-94560: Twisted Metal 4 (USA)

### ISSUE THREAD

**Issue by TruKuu** [HeatXD/duckstation-fightcade-savestates#179]
**Hash**

MD5: 719cbff7e7c8463407dafdaa61d8ff25

**Description**

All Cars unlocked
All Worlds unlocked
New Game highlights 2 Player Deathmatch

Deathmatch options:
- Difficulty: Hard
- Chosen World: Advances
- CPU Enemies Chosen: By Player

Tournament options:
- CPU Ally: No
- Pool Lives: Yes

Video Settings:
- Refresh Priority: Gameplay
- Dithering: On

Savestate boots to the main menu with "New Game" highlighted

**Savestate**
[SCUS-94560_1.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11295260/SCUS-94560_1.zip)

**Comment by bigbangblitz** [comment]
this is one of those games that has a newer revision
