### ISSUE TITLE
SCUS-94570: Crash Bash (USA)

### ISSUE THREAD

**Issue by TruKuu** [HeatXD/duckstation-fightcade-savestates#323]
**Hash**

MD5: 62a975ef46da8d6370d5a3a5a4cd91f0

**Description**

All Minigames unlocked
Cheats enabled to remove the need for a memory card
Savestate boots at the title screen

**Savestate**
[SCUS-94570_1.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11364452/SCUS-94570_1.zip)

**Cheat File**
[CrashBashCheats.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11364456/CrashBashCheats.zip)

**Comment by HeatXD** [comment]
closing dupe
