### ISSUE TITLE
Real Bout Garou Densetsu Special - Dominated Mind (Japan) (Shokai Genteiban) SLPM-86090

### ISSUE THREAD

**Issue by Combone** [HeatXD/duckstation-fightcade-savestates#34]
**Hash**

MD5: 23BBF6A6EF1813298BB5501B36012375

**Description**

Game Start in Vs. Mode. All secret moves unlocked (I found save on the internet a long time ago, not who made it. Sorry).

**Savestate**

[SLPM-86090_1.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11198988/SLPM-86090_1.zip)

**Comment by HeatXD** [comment]
Doesn't comply to the requirements closing.
