### ISSUE TITLE
SCUS-94426: CTR - Crash Team Racing (USA)

### ISSUE THREAD

**Issue by FRDS** [HeatXD/duckstation-fightcade-savestates#424]
### Hash
MD5: 7f2419222892f31e12e025255c606c35

### Description
- Unlocks all characters, tracks, cups and difficulties.
- Cheats enabled, no need for memory card.
- Boots at title screen

### Savestate
[SCUS-94426.zip](https://github.com/HeatXD/duckstation-fightcade-savestates/files/11581222/SCUS-94426.zip)

**Comment by bigbangblitz** [comment]
Closed for duplicate issue of https://github.com/HeatXD/duckstation-fightcade-savestates/issues/164
